### PR TITLE
Allow bytes input for image embedding

### PR DESCRIPTION
**Pull request by KaQuMiQ**

### CODE REVIEW

**Comment by joein** [comment]
Hi @KaQuMiQ 

Thanks for the interest in the project!

However, I am afraid a new type introduction is more complicated, since it should handle the parallelization, and take into account the preprocessing operations which are applied to the input

**Comment by KaQuMiQ** [comment]
Right, I have missed that part. I believe specifying it to be BytesIO should be enough - I was testing on this implementation in particular. Would it be a good solution for you?

**Comment by joein** [comment]
I think we can add it, if it works without tricks

Could you add some tests to verify that it works (both in a regular case, and in a parallel execution case), please?

**Comment by KaQuMiQ** [comment]
> Could you add some tests to verify that it works (both in a regular case, and in a parallel execution case), please?

Sure! Sorry for the delay, I will add those and update PR as soon as I will be able to.

**Comment by joein** [comment]
Closing in favour of #315 

Thanks for the attempt!

**Pull request closed without merging**
