### PR TITLE
fix: remove model archive if model extraction was not finished correctly

### PR DESCRIPTION
**Pull request by joein**

### CODE REVIEW

**Comment by Anush008** [comment]
I am unsure about the new `force` param. It would only affect GCS downloads correct? We won't be adding any new models there and people could expect it to work for all the models.

**Comment by joein** [comment]
@Anush008 

Yeah, I think HF downloader handles these erroneous situations on its own, so it is only valid for GCS

I am not sure if we are not going to add any fallback links, cause otherwise we will have a single point of denial (hf hub)

I am also not completely sure on this param, that was one of the reasons why I hid it in kwargs and did not expose it to `__init__` params

**Comment by Anush008** [comment]
I don't recall if there was any discussion about the links.
Just that we didn't add any new GCS sources after HuggingFace sources were introduced.

**Comment by joein** [comment]
Ok, let's drop it, and see if someone actually encounters this problem

**Comment by Anush008** [comment]
@joein, I found the HF library also accepts a `force_download` param. Could be put to use.

**Comment by joein** [comment]
@Anush008 the problem was related to GCS, not HF, HF works fine

**Comment by Anush008** [comment]
Right. I meant if we ever need to introduce a `force_download` param, we can.

**Pull request merged**
