### PR TITLE
ONNX-GPU

### LINKED ISSUE #52: Feature: Option for ONNX on GPU execution provider
I appreciate the CPU-first design. 

It would be great to switch the execution provider to `GPU/CUDA` - are there any plans on the roadmap to do so?

### PR DESCRIPTION
**Pull request by michaelfeil**
This PR aims to add **optional** GPU support, only if onnxruntime-gpu is installed. Reference: https://github.com/michaelfeil/infinity/pull/26

Closes #52

### CODE REVIEW

**Comment by equal-l2** [comment]
You might want to add the `extras` section to the `pyproject.toml`, to indicate this package can use `onnxruntime-gpu` as an optional dependecy.
For details about extras section in pyproject.toml, see <https://python-poetry.org/docs/pyproject/#extras>.

**Comment by michaelfeil** [comment]
Yes, I have done this in my personal package. Note that I stopped contributing here, as none of the PRs was getting attention.

**Comment by logan-markewich** [comment]
would be cool if this got merged...

**Comment by generall** [comment]
I have the following concerns before merging this PR:

- Does it introduce new cuda-related dependencies into the package?
  - If not, how can it work with cuda? 
  - Does it requires manual installation of dependencies? If so, this should be documented.
  - If it introduces new dependencies, is it possible to make them optional? Usually cuda-related packages are very big and I would prefer to avoid them if I am working in CPU-only environment
- If I have GPU on my machine, how can I force it to use CPU-only? This should be documented

**Comment by pazoff** [comment]
It would be very, very cool if this got merged...

**Comment by NirantK** [comment]
Closing this in favour of #214, closes #52 and #97

**Pull request closed without merging**
