### PR TITLE
include python 3.12 into deps and ci

### PR DESCRIPTION
**Pull request by generall**

### CODE REVIEW

**Comment by NirantK** [comment]
ONNXRuntime does not support 3.12 yet: https://github.com/microsoft/onnxruntime/blob/db3901ab9790fef952aa6a0147eedf671c17c899/pyproject.toml#L5

**Comment by NirantK** [comment]
Will prefer to wait for ONNXRuntime to support 3.12 before supporting 3.12 ourselves and making a 0.1 release

**Comment by generall** [comment]
Related issue: https://github.com/microsoft/onnxruntime/issues/17842

**Comment by michaelfeil** [comment]
@NirantK Can you pin at least in this way, and free your own package. Would make it more clear, but has identical effect.

```python
onnxruntime-gpu = {version = "*", python = ">=3.8,<3.12"}
```

**Comment by NirantK** [comment]
> onnxruntime = {version = "*", python = ">=3.8,<3.12"}

This gets overwritten every time we use poetry to upgrade packages to: 

> onnxruntime = "^1.16.3"

The Python version lock is indeed described as you'd mentioned: 

> python = ">=3.8.0,<3.12"

We'd not want to remove the version lock completely on `onnxruntime` for reproducibility of issues. Without that, a fastembed version could map to any onnxruntime version and we'd not be able to debug if it was a version issue.

**Comment by NirantK** [comment]
FastEmbed now supports Python3.12 and this PR/branch is no longer relevant and updated. Closing this without merging.

**Pull request closed without merging**
